"""
Centralized configuration constants for the delivery_robots project.
All magic numbers, default values, and static literals are consolidated here for maintainability.
Organized by domain.
"""

# ── Graph Construction (OSMnx) ──
GRAPH_CENTER = (21.0285, 105.8542)
GRAPH_DIST_METERS = 2200
GRAPH_NETWORK_TYPE = "bike"

# ── Simulation Time ──
SIMULATION_SPEED = 30
SIMULATION_START_OFFSET_SECONDS = 21600  # 6:00 AM expressed as seconds from midnight
SECONDS_PER_DAY = 86400
SECONDS_PER_HOUR = 3600
SECONDS_PER_MINUTE = 60

# ── Rush Hour ──
RUSH_HOURS = [
    {"name": "Morning Rush", "start": 7, "end": 9, "multiplier": 2.5},
    {"name": "Lunch Traffic", "start": 11, "end": 13, "multiplier": 1.3},
    {"name": "Evening Rush", "start": 17, "end": 19, "multiplier": 3.0},
]
DEFAULT_RUSH_HOUR_MULTIPLIER = 1.0
DEFAULT_RUSH_HOUR_LABEL = "Normal"
RUSH_HOUR_INACTIVE_LABEL = "Normal"

# ── Traffic ──
TRAFFIC_ANCHORS = []
TRAFFIC_PERIOD_SECONDS = 36
DEFAULT_TRAFFIC_PENALTY = 1.0
TRAFFIC_ACTIVE_SEGMENT_THRESHOLD = 0.9
TRAFFIC_INFLUENCE_RADIUS_METERS = 24
TRAFFIC_MIN_SEGMENT_STRENGTH = 0.35
TRAFFIC_SEVERITY_SCALING_FACTOR = 3.2
TRAFFIC_SEGMENT_STRENGTH_THRESHOLD = 0.15
TRAFFIC_ROUTE_NAME_PREFIX = "Traffic "
DEFAULT_TRAFFIC_SEVERITY = 0.7
TRAFFIC_SEVERITY_CLAMP_MIN = 0.0
TRAFFIC_SEVERITY_CLAMP_MAX = 1.0
DEFAULT_RANDOMIZE_TRAFFIC_COUNT = 3
RANDOM_TRAFFIC_SEVERITY_MIN = 0.4
RANDOM_TRAFFIC_SEVERITY_MAX = 0.9
RANDOM_TRAFFIC_LAT_MIN = 21.0200
RANDOM_TRAFFIC_LAT_MAX = 21.0350
RANDOM_TRAFFIC_LON_MIN = 105.8450
RANDOM_TRAFFIC_LON_MAX = 105.8600
RANDOM_TRAFFIC_PATH_POINT_COUNT = 10

# ── Weather / Rain ──
RAIN_ZONES_INITIAL = []
DEFAULT_RAIN_PENALTY = 1.0
DEFAULT_RAIN_SEVERITY = 1.0
DEFAULT_WEATHER_RAIN_SEVERITY = 1.0
RAIN_ZONE_NAME_PREFIX = "Rain "
DEFAULT_RAIN_RADIUS = 150
DEFAULT_RANDOMIZE_RAIN_COUNT = 3
DEFAULT_RAIN_MIN_RADIUS = 100
DEFAULT_RAIN_MAX_RADIUS = 200

# ── Obstacles ──
DEFAULT_OBSTACLE_PENALTY = 1.0
DEFAULT_OBSTACLE_SEVERITY = 10.0
OBSTACLE_SEVERITY_DIVISOR = 10.0
OBSTACLE_MIN_CLOSENESS_FACTOR = 0.2
OBSTACLE_NAME_PREFIX = "Obstacle "
OBSTACLE_RANDOMIZE_NAME_PREFIX = "Obs "
DEFAULT_OBSTACLE_RADIUS = 80
DEFAULT_OBSTACLE_TYPE = "roadblock"
DEFAULT_RANDOMIZE_OBSTACLE_COUNT = 3
OBSTACLE_TYPES = ["roadblock", "construction", "accident"]
RANDOM_OBSTACLE_RADIUS_MIN = 50
RANDOM_OBSTACLE_RADIUS_MAX = 120
RANDOM_OBSTACLE_SEVERITY_MIN = 5
RANDOM_OBSTACLE_SEVERITY_MAX = 50

# ── Routing ──
DEFAULT_EDGE_LENGTH = 0.0
DEFAULT_ROUTE_DISTANCE = 0.0
SPEED_METERS_PER_SECOND = 2

# ── Hub Optimization ──
DEFAULT_HUB_CLUSTER_COUNT = 5
MIN_DELIVERY_HISTORY_POINTS = 5
MIN_DELIVERY_HISTORY_ERROR_MSG = (
    "Not enough delivery data to optimize hubs. Need at least "
    + str(MIN_DELIVERY_HISTORY_POINTS)
    + " points."
)
KMEANS_RANDOM_STATE = 42
KMEANS_N_INIT = "auto"
HUB_NAME_PREFIX = "AI Hub "
HUB_NAME_ASCII_OFFSET = 65  # ASCII code for 'A'

# ── Geography / Geodesy ──
EARTH_RADIUS_METERS = 6371009
METERS_PER_DEGREE_LATITUDE = 111320
RANDOM_LAT_MIN = 21.0180
RANDOM_LAT_MAX = 21.0380
RANDOM_LON_MIN = 105.8430
RANDOM_LON_MAX = 105.8650

# ── Validation ──
LATITUDE_MIN = -90
LATITUDE_MAX = 90
LATITUDE_ERROR_MSG = "Latitude must be between -90 and 90"
LONGITUDE_MIN = -180
LONGITUDE_MAX = 180
LONGITUDE_ERROR_MSG = "Longitude must be between -180 and 180"

# ── Metrics ──
METRICS_INITIAL_MIN_CALC_TIME = 999
METRICS_PATH_LENGTHS_MAX_SIZE = 100

# ── API / Logs ──
API_LOGS_MAX_LENGTH = 500
TIMESTAMP_MS_MULTIPLIER = 1000
DEFAULT_LOG_LEVEL = "info"
DEFAULT_LOG_SOURCE = "frontend"
DEFAULT_LOGS_LIMIT = 200
LOGS_LIMIT_MIN = 1
LOGS_LIMIT_MAX = 1000

# ── Robot Statuses ──
ROBOT_STATUS_IDLE = "idle"
ROBOT_STATUS_MOVING_TO_PICKUP = "moving_to_pickup"
ROBOT_STATUS_MOVING_TO_DROPOFF = "moving_to_dropoff"
ROBOT_STATUS_MOVING_TO_CHARGE = "moving_to_charge"
ROBOT_STATUS_CHARGING = "charging"
