"""
Centralized configuration constants for the delivery_robots project.
All magic numbers, default values, and static literals are consolidated here for maintainability.
Organized by domain.
"""

# ── Graph Construction (OSMnx) ──
GRAPH_CENTER = (21.0285, 105.8542)
GRAPH_DIST_METERS = 2200
GRAPH_NETWORK_TYPE = "bike"
GRAPH_CACHE_ENABLED = True
GRAPH_CACHE_DIR = "cache"
GRAPH_CACHE_FILENAME = (
    f"osmnx_{GRAPH_CENTER[0]:.4f}_{GRAPH_CENTER[1]:.4f}_"
    f"{GRAPH_NETWORK_TYPE}_{GRAPH_DIST_METERS}m.graphml"
)

# ── Simulation Time ──
SIMULATION_SPEED = 60
SIMULATION_START_OFFSET_SECONDS = 21600  # 6:00 AM expressed as seconds from midnight
SECONDS_PER_DAY = 86400
SECONDS_PER_HOUR = 3600
SECONDS_PER_MINUTE = 60

# ── Rush Hour ──
RUSH_HOURS = [
    {"name": "Morning Rush", "start": 7, "end": 9, "multiplier": 2.5},
    {"name": "Lunch Traffic", "start": 11, "end": 13, "multiplier": 1.3},
    {"name": "Evening Rush", "start": 17, "end": 19, "multiplier": 3.0},
]
DEFAULT_RUSH_HOUR_MULTIPLIER = 1.0
DEFAULT_RUSH_HOUR_LABEL = "Normal"
RUSH_HOUR_INACTIVE_LABEL = "Normal"

# ── Traffic ──
TRAFFIC_ANCHORS = []
TRAFFIC_PERIOD_SECONDS = 36
DEFAULT_TRAFFIC_PENALTY = 1.0
TRAFFIC_ACTIVE_SEGMENT_THRESHOLD = 0.9
TRAFFIC_INFLUENCE_RADIUS_METERS = 24
TRAFFIC_MIN_SEGMENT_STRENGTH = 0.35
TRAFFIC_SEVERITY_SCALING_FACTOR = 3.2
TRAFFIC_SEGMENT_STRENGTH_THRESHOLD = 0.15
TRAFFIC_ROUTE_NAME_PREFIX = "Traffic "
DEFAULT_TRAFFIC_SEVERITY = 0.7
TRAFFIC_SEVERITY_CLAMP_MIN = 0.0
TRAFFIC_SEVERITY_CLAMP_MAX = 1.0
DEFAULT_RANDOMIZE_TRAFFIC_COUNT = 3
RANDOM_TRAFFIC_SEVERITY_MIN = 0.4
RANDOM_TRAFFIC_SEVERITY_MAX = 0.9
RANDOM_TRAFFIC_LAT_MIN = 21.0200
RANDOM_TRAFFIC_LAT_MAX = 21.0350
RANDOM_TRAFFIC_LON_MIN = 105.8450
RANDOM_TRAFFIC_LON_MAX = 105.8600
RANDOM_TRAFFIC_PATH_POINT_COUNT = 10

# ── Weather / Rain ──
RAIN_ZONES_INITIAL = []
DEFAULT_RAIN_PENALTY = 1.0
DEFAULT_RAIN_SEVERITY = 1.0
DEFAULT_WEATHER_RAIN_SEVERITY = 1.0
RAIN_ZONE_NAME_PREFIX = "Rain "
DEFAULT_RAIN_RADIUS = 150
DEFAULT_RANDOMIZE_RAIN_COUNT = 3
DEFAULT_RAIN_MIN_RADIUS = 100
DEFAULT_RAIN_MAX_RADIUS = 200

# ── Obstacles ──
DEFAULT_OBSTACLE_PENALTY = 1.0
DEFAULT_OBSTACLE_SEVERITY = 10.0
OBSTACLE_SEVERITY_DIVISOR = 10.0
OBSTACLE_MIN_CLOSENESS_FACTOR = 0.2
OBSTACLE_NAME_PREFIX = "Obstacle "
OBSTACLE_RANDOMIZE_NAME_PREFIX = "Obs "
DEFAULT_OBSTACLE_RADIUS = 80
DEFAULT_OBSTACLE_TYPE = "roadblock"
DEFAULT_RANDOMIZE_OBSTACLE_COUNT = 3
OBSTACLE_TYPES = ["roadblock", "construction", "accident"]
RANDOM_OBSTACLE_RADIUS_MIN = 50
RANDOM_OBSTACLE_RADIUS_MAX = 120
RANDOM_OBSTACLE_SEVERITY_MIN = 5
RANDOM_OBSTACLE_SEVERITY_MAX = 50

# ── Charging Stations ──
CHARGING_STATIONS_INITIAL = [
    {"id": 1, "lat": 21.0285, "lon": 105.8542, "name": "Hoan Kiem Hub", "spots": 3},
    {"id": 2, "lat": 21.0355, "lon": 105.8516, "name": "Dong Xuan", "spots": 2},
    {"id": 3, "lat": 21.0240, "lon": 105.8480, "name": "Trang Tien", "spots": 2},
    {"id": 4, "lat": 21.0220, "lon": 105.8510, "name": "Ly Thuong Kiet", "spots": 2},
    {"id": 5, "lat": 21.0300, "lon": 105.8530, "name": "Hang Ngang", "spots": 2},
    {"id": 6, "lat": 21.0275, "lon": 105.8520, "name": "Opera House", "spots": 2},
]

# ── Routing ──
DEFAULT_ROUTING_ALGORITHM = "astar"
VALID_ROUTING_ALGORITHMS = {"astar", "gbfs", "dijkstra"}
ROUTING_ALGORITHM_ALIASES = {"greedy": "gbfs"}
INVALID_ALGORITHM_ERROR = "Invalid algo. Use astar, gbfs, or dijkstra."
DEFAULT_ROAD_MEMORY_PENALTY = 1.0
DEFAULT_EDGE_LENGTH = 0.0
DEFAULT_ROUTE_DISTANCE = 0.0
ESTIMATED_SPEED_METERS_PER_MINUTE = 180

# ── Dispatch ──
DISPATCH_MAX_ROUTE_CANDIDATES_PER_DELIVERY = 4
DISPATCH_HIGH_PRIORITY_SCORE_THRESHOLD = 20
DISPATCH_HIGH_PRIORITY_EXTRA_CANDIDATES = 1
DISPATCH_PICKUP_CATEGORY_WEIGHTS = {
    "restaurant": 9,
    "market": 7,
    "retail": 6,
    "office": 5,
    "hotel": 5,
    "landmark": 3,
    "residential": 4,
}
DISPATCH_DROPOFF_CATEGORY_WEIGHTS = {
    "residential": 8,
    "hotel": 6,
    "office": 5,
    "retail": 4,
    "restaurant": 4,
    "landmark": 2,
    "market": 3,
}
DISPATCH_DEFAULT_CATEGORY_WEIGHT = 4
DISPATCH_WAIT_MINUTES_WEIGHT = 2.8
DISPATCH_BATTERY_DRAIN_PER_KM = 4.5
DISPATCH_BATTERY_SAFETY_MARGIN = 0.35
DISPATCH_BATTERY_RISK_WEIGHT = 120
DISPATCH_PRIORITY_WEIGHT = 18
DISPATCH_MIN_BATTERY_PERCENT = 15
DISPATCH_MIN_PROJECTED_BATTERY_PERCENT = 15
DISPATCH_MAX_ROUTE_ETA_MINUTES = 12
DISPATCH_MAX_PICKUP_DISTANCE_METERS = 2600
DISPATCH_REQUIRED_ROBOT_STATUS = "idle"

# ── Hub Optimization ──
DEFAULT_HUB_CLUSTER_COUNT = 5
MIN_DELIVERY_HISTORY_POINTS = 5
MIN_DELIVERY_HISTORY_ERROR_MSG = (
    "Not enough delivery data to optimize hubs. Need at least "
    + str(MIN_DELIVERY_HISTORY_POINTS)
    + " points."
)
KMEANS_RANDOM_STATE = 42
KMEANS_N_INIT = "auto"
HUB_NAME_PREFIX = "AI Hub "
HUB_NAME_ASCII_OFFSET = 65  # ASCII code for 'A'

# ── Geography / Geodesy ──
EARTH_RADIUS_METERS = 6371000
METERS_PER_DEGREE_LATITUDE = 111320
RANDOM_LAT_MIN = 21.0180
RANDOM_LAT_MAX = 21.0380
RANDOM_LON_MIN = 105.8430
RANDOM_LON_MAX = 105.8650

# ── Validation ──
LATITUDE_MIN = -90
LATITUDE_MAX = 90
LATITUDE_ERROR_MSG = "Latitude must be between -90 and 90"
LONGITUDE_MIN = -180
LONGITUDE_MAX = 180
LONGITUDE_ERROR_MSG = "Longitude must be between -180 and 180"

# ── Metrics ──
METRICS_INITIAL_MIN_CALC_TIME = 999
METRICS_PATH_LENGTHS_MAX_SIZE = 100

# ── API / Logs ──
API_LOGS_MAX_LENGTH = 500
TIMESTAMP_MS_MULTIPLIER = 1000
DEFAULT_LOG_LEVEL = "info"
DEFAULT_LOG_SOURCE = "frontend"
DEFAULT_LOGS_LIMIT = 200
LOGS_LIMIT_MIN = 1
LOGS_LIMIT_MAX = 1000
PERSISTENT_LOG_DIR = "logs"
APP_EVENTS_LOG_FILENAME = "app-events.jsonl"
DELIVERY_HISTORY_LOG_FILENAME = "delivery-history.jsonl"

# ── VRP / Simulated Annealing ──
VRP_ENABLED = True
VRP_MAX_ORDERS_PER_ROBOT = 3
VRP_MIN_ORDERS_FOR_SA = 2
VRP_SA_INITIAL_TEMP = 500
VRP_SA_MIN_TEMP = 0.01
VRP_SA_COOLING_RATE = 0.995
VRP_SA_ITERATIONS_PER_TEMP = 50
VRP_SA_MAX_ITERATIONS = 5000

# ── Demo Defaults ──
DEFAULT_DEMO_FROM_LAT = 21.0285
DEFAULT_DEMO_FROM_LON = 105.8542
DEFAULT_DEMO_TO_LAT = 21.0355
DEFAULT_DEMO_TO_LON = 105.8516
INVALID_COORDS_ERROR = "Invalid coords"
CLASSICAL_COMPARE_NOTE = (
    "Classical AI compare uses base edge length only (no rain/traffic/obstacle penalties)."
)

# ── Insider / XAI Demos ──
ASTEP_MAX_STEPS = 30
INSIDER_FALLBACK_EDGE_LENGTH = 10
INSIDER_COORD_ROUND_DECIMALS = 5
INSIDER_SCORE_ROUND_DECIMALS = 1
INSIDER_TIME_ROUND_DECIMALS = 2
